insert into "Genres" ("Id", "Name")
values ('4d0ef30a-c50c-4e30-9c73-47c6e24f82b2', 'Pop'),
       (default, 'Country'),
       (default, 'Electronic music'),
       (default, 'Jazz'),
       (default, 'Indie folk'),
       (default, 'Country blues'),
       (default, 'Hip hop'),
       (default, 'Latin music'),
       (default, 'Reggae'),
       (default, 'Rock'),
       (default, 'Soul'),
       (default, 'Classical music'),
       (default, 'Rhythm and blues'),
       (default, 'Choral'),
       (default, 'Disco'),
       (default, 'Funk'),
       (default, 'Metal'),
       (default, 'New-age music'),
       (default, 'Acousmatic music')
;